# Generated by Django 2.0.7 on 2018-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='url',
            field=models.CharField(max_length=300, verbose_name='活动链接'),
        ),
        migrations.AlterField(
            model_name='indextypegoodsbanner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间记录'),
        ),
        migrations.AlterField(
            model_name='indextypegoodsbanner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时记录'),
        ),
    ]
