# Generated by Django 2.0.7 on 2018-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180802_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default=True, max_length=256, verbose_name='评论'),
        ),
    ]
